live_config_reload: true
env:
  TERM: xterm-256color

window:
  opacity: 0.9
  decorations: buttonless
  dynamic_padding: false

shell:
  program: /usr/local/bin/zsh
  args:
    - -l
    - -c
    - "tmux attach -t base || tmux new -s base"

font:
  normal:
    family: "DankMono Nerd Font Mono"
    style: Regular
  bold:
    family: "DankMono Nerd Font Mono"
    style: Bold
  italic:
    family: "DankMono Nerd Font Mono"
    style: Italic
  size: 22.0
  builtin_box_drawing: true
  offset:
    x: 0
    y: 0

selection:
  save_to_clipboard: true

key_bindings:
  # macOS
  - { key: Equals, mods: Command, action: IncreaseFontSize }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: NumpadAdd, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: NumpadSubtract, mods: Command, action: DecreaseFontSize }
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }
  - { key: H, mods: Command, action: Hide }
  - { key: M, mods: Command, action: Minimize }
  - { key: Q, mods: Command, action: Quit }
  - { key: F, mods: Command|Control, action: ToggleFullscreen }
  - { key: F, mods: Command, action: SearchForward }
  - { key: B, mods: Command, action: SearchBackward }
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left, mods: Alt, chars: "\x1BB" }

  # Tmux
  - { key: K, mods: Command, chars: "\x02\x73" } # Select a new tmux session for the attached client interactively
  - { key: Key1, mods: Command, chars: "\x02\x31" } # Select window 1
  - { key: Key2, mods: Command, chars: "\x02\x32" } # Select window 2
  - { key: Key3, mods: Command, chars: "\x02\x33" } # Select window 3
  - { key: Key4, mods: Command, chars: "\x02\x34" } # Select window 4
  - { key: Key5, mods: Command, chars: "\x02\x35" } # Select window 5
  - { key: Key6, mods: Command, chars: "\x02\x36" } # Select window 6
  - { key: Key7, mods: Command, chars: "\x02\x37" } # Select window 7
  - { key: Key8, mods: Command, chars: "\x02\x38" } # Select window 8
  - { key: Key9, mods: Command, chars: "\x02\x39" } # Select window 9
  - { key: L, mods: Command, chars: "\x02\x4c" } # Switch to last tmux session
  - { key: LBracket, mods: Command, chars: "\x02\x5b" } # Switch to last tmux session
  - { key: LBracket, mods: Command|Shift, chars: "\x02\x70" } # Change to the previous tmux window
  - { key: N, mods: Command|Shift, chars: "\x02\x25" } # Split the current pane into two, left and right
  - { key: D, mods: Command, chars: "\x02\x25" } # Split the current pane into two, left and right
  - { key: N, mods: Command, chars: "\x02\x22" } # Split the current pane into two, top and bottom
  - { key: D, mods: Command|Shift, chars: "\x02\x22" } # Split the current pane into two, top and bottom
  - { key: Q, mods: Command, chars: "\x02\x64" } # Detach the current tmux client
  - { key: RBracket, mods: Command|Shift, chars: "\x02\x6e" } # Change to the next tmux window
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" } # Type <escape>:w<enter> to save neovim
  - { key: T, mods: Command, chars: "\x02\x63" } # Create a new tmux window
  - { key: T, mods: Command|Shift, chars: "\x02\x21" } # Break the current tmux pane out of the tmux window
  - { key: W, mods: Command, chars: "\x02\x78" } # Kill the current tmux pane (and window if last pane)
  - { key: Z, mods: Command, chars: "\x02\x7a" } # Toggle the zoom state of the current tmux pane

schemes:
  nightfly: &nightfly
    # Default colors
    # Default colors
    primary:
      background: "#011627"
      foreground: "#acb4c2"
      bright_foreground: "#eeeeee"

    # Cursor colors
    cursor:
      text: "#080808"
      cursor: "#9ca1aa"

    # Selection colors
    selection:
      text: "#080808"
      background: "#b2ceee"

    # Normal colors
    normal:
      black: "#1d3b53"
      red: "#fc514e"
      green: "#a1cd5e"
      yellow: "#e3d18a"
      blue: "#82aaff"
      magenta: "#c792ea"
      cyan: "#7fdbca"
      white: "#a1aab8"

    # Bright colors
    bright:
      black: "#7c8f8f"
      red: "#ff5874"
      green: "#21c7a8"
      yellow: "#ecc48d"
      blue: "#82aaff"
      magenta: "#ae81ff"
      cyan: "#7fdbca"
      white: "#d6deeb"
  tokyonight-day: &tokyonight-day # Default colors
    primary:
      background: "0xe1e2e7"
      foreground: "0x3760bf"

    # Normal colors
    normal:
      black: "0xe9e9ed"
      red: "0xf52a65"
      green: "0x587539"
      yellow: "0x8c6c3e"
      blue: "0x2e7de9"
      magenta: "0x9854f1"
      cyan: "0x007197"
      white: "0x6172b0"

    # Bright colors
    bright:
      black: "0xa1a6c5"
      red: "0xf52a65"
      green: "0x587539"
      yellow: "0x8c6c3e"
      blue: "0x2e7de9"
      magenta: "0x9854f1"
      cyan: "0x007197"
      white: "0x3760bf"

    indexed_colors:
      - { index: 16, color: "0xb15c00" }
      - { index: 17, color: "0xc64343" }
  tokyonight-night: &tokyonight-night # Default colors
    primary:
      background: "0x1a1b26"
      foreground: "0xc0caf5"

    # Normal colors
    normal:
      black: "0x15161e"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xa9b1d6"

    # Bright colors
    bright:
      black: "0x414868"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xc0caf5"

    indexed_colors:
      - { index: 16, color: "0xff9e64" }
      - { index: 17, color: "0xdb4b4b" }
  tokyonight-storm: &tokyonight-storm # Default colors
    primary:
      background: "0x24283b"
      foreground: "0xc0caf5"

    # Normal colors
    normal:
      black: "0x1d202f"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xa9b1d6"

    # Bright colors
    bright:
      black: "0x414868"
      red: "0xf7768e"
      green: "0x9ece6a"
      yellow: "0xe0af68"
      blue: "0x7aa2f7"
      magenta: "0xbb9af7"
      cyan: "0x7dcfff"
      white: "0xc0caf5"

    indexed_colors:
      - { index: 16, color: "0xff9e64" }
      - { index: 17, color: "0xdb4b4b" }

draw_bold_text_with_bright_colors: true
colors: *nightfly
